site_name: 'OVHcloud #TechRoadShow'
nav:
  - 'Introduction':
    - index.md
    - Linux, Unix, MacOS: unix.md
    - Windows: windows.md
theme:
  name: material
  favicon: img/favicon.ico
  palette:
    scheme: slate
