site_name: 'OVHcloud #TechRoadShow'
nav:
  - 'Wprowadzenie': index.md
  - 'Instrukcje':
    - env.md
    - basic.md
    - vrack.md
    - horizon.md
    - cli.md
    - swift.md
    - k8s.md
theme:
  name: material
  favicon: img/favicon.ico
  logo: img/logo.svg
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night


        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css
