site_name: 'OVHcloud #TechRoadShow'
site_url: https://ovhtechroadshow.github.io/
nav:
  - Linux, Unix, MacOS: unix.md
  - Windows: windows.md
theme:
  name: material
  favicon: img/favicon.ico
  palette:
    scheme: slate
